### ISSUE TITLE
Replacing words long list with a lightweight sqlite3 database

### ISSUE THREAD

**Issue by Ali-Xoerex** [afred-khan/Hangman#3]
Do you agree with me that it's better to have a lighweight database of words such as an instance of sqlite3 instead of loading the whole list into memory?
So that when the words list grows , probable memory issues won't happen

**Comment by afred-khan** [comment]
@Ali-Xoerex That's correct! I'll assign you the task if you want to work on this.

**Comment by Ali-Xoerex** [comment]
Nice! I'll send a PR when it's complete

**Comment by Ali-Xoerex** [comment]
#7 added SQLite support. now the game gets it's word from database instead of memory

**Comment by afred-khan** [comment]
@Ali-Xoerex Well done!
